import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Navigate, Route, Routes } from 'react-router-dom';
import { api, API_BASE, listFiles, listKnowledgeBases, listTools, streamCompletion, uploadDocuments, unwrap } from './api';
import './styles.css';

const nav = [['/chat', '◈', 'General Chat'], ['/rag', '◇', 'RAG Chat'], ['/knowledge-base', '▣', 'Knowledge Base'], ['/mcp', '⌘', 'MCP Management'], ['/api-keys', '⚿', 'API Keys']];
const id = () => crypto.randomUUID?.() || Math.random().toString(36).slice(2);
const getSessions = (key) => JSON.parse(localStorage.getItem(key) || '[]');

function Layout({ children }) { return <div className="shell"><aside className="sidebar"><NavLink to="/chat" className="brand"><img src="/orvix-logo.png"/><span>Orvix<small>AI WORKSPACE</small></span></NavLink><nav>{nav.map(([to, icon, label]) => <NavLink key={to} to={to} className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}><b>{icon}</b>{label}</NavLink>)}</nav><div className="api-status"><i/> FastAPI connected<br/><span>{API_BASE}</span></div></aside><main>{children}</main></div> }

function Markdown({ text }) { return <div className="markdown">{text.split('\n').map((line, i) => <React.Fragment key={i}>{line}{i < text.split('\n').length - 1 && <br/>}</React.Fragment>)}</div> }

function ChatPage({ rag = false }) {
  const store = rag ? 'orvix-rag-sessions' : 'orvix-chat-sessions';
  const [sessions, setSessions] = useState(() => getSessions(store));
  const [active, setActive] = useState(() => getSessions(store)[0]?.id || '');
  const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [tools, setTools] = useState({}); const [selectedTools, setSelectedTools] = useState([]); const [agent, setAgent] = useState(false);
  const [settings, setSettings] = useState({ model: '', temperature: .7, history: 5, kb: '', mode: 'kb', topK: 3, threshold: 1, direct: false });
  const bottom = useRef();
  const current = sessions.find(s => s.id === active);
  const persist = (next) => { setSessions(next); localStorage.setItem(store, JSON.stringify(next)); };
  const newSession = () => { const s = { id: id(), name: `Conversation ${sessions.length + 1}`, messages: [] }; persist([s, ...sessions]); setActive(s.id); };
  const update = (fn) => persist(sessions.map(s => s.id === active ? fn(s) : s));
  useEffect(() => { if (!active && !sessions.length) newSession(); }, []);
  useEffect(() => { if (!rag) listTools().then(setTools).catch(() => {}); else listKnowledgeBases().then(items => setSettings(s => ({ ...s, kb: s.kb || items[0]?.kb_name || '' }))).catch(() => {}); }, [rag]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }); }, [current?.messages.length, busy]);
  const send = async () => {
    const prompt = input.trim(); if (!prompt || busy || !current) return;
    setError(''); setInput(''); setBusy(true); const user = { role: 'user', content: prompt }; const assistant = { role: 'assistant', content: '' };
    const history = current.messages.slice(-settings.history).map(({role, content}) => ({ role, content }));
    update(s => ({ ...s, messages: [...s.messages, user, assistant] }));
    const write = (value) => update(s => ({ ...s, messages: s.messages.map((m, i) => i === s.messages.length - 1 ? { ...m, content: value } : m) }));
    try {
      if (rag) {
        let endpoint; if (settings.mode === 'file') { setError('Upload files from the knowledge-base page, then select a saved knowledge base.'); setBusy(false); return; }
        endpoint = settings.mode === 'search' ? `/knowledge_base/search_engine/duckduckgo/chat/completions` : `/knowledge_base/local_kb/${encodeURIComponent(settings.kb)}/chat/completions`;
        let output = ''; await streamCompletion(endpoint, { messages: [...history, user], model: settings.model || 'default', stream: true, extra_body: { top_k: settings.topK, score_threshold: settings.threshold, return_direct: settings.direct, temperature: settings.temperature, prompt_name: 'default' } }, d => { output += d.choices?.[0]?.delta?.content || ''; write(output); });
      } else {
        let output = ''; await streamCompletion('/chat/completions', { messages: [...history, user], model: settings.model || 'default', stream: true, tools: selectedTools.length ? selectedTools : undefined, tool_choice: selectedTools.length === 1 ? selectedTools[0] : undefined, extra_body: { conversation_id: current.id, use_mcp: agent, chat_model_config: { llm_model: {} } } }, d => { output += d.choices?.[0]?.delta?.content || ''; write(output); });
      }
    } catch (e) { setError(e.message || 'The server could not complete this request.'); write(''); }
    finally { setBusy(false); }
  };
  return <div className="chat-page"><header className="page-head"><div><p className="eyebrow">{rag ? 'RETRIEVAL AUGMENTED GENERATION' : 'AI CONVERSATION'}</p><h1>{rag ? 'RAG Chat' : 'General Chat'}</h1></div><button className="primary" onClick={newSession}>+ New conversation</button></header><div className="chat-layout"><section className="session-panel"><strong>CONVERSATIONS</strong>{sessions.map(s => <button className={s.id === active ? 'session active-session' : 'session'} onClick={() => setActive(s.id)} key={s.id}>{s.name}<span onClick={(e) => { e.stopPropagation(); persist(sessions.filter(x => x.id !== s.id)); if (active === s.id) setActive(sessions.find(x => x.id !== s.id)?.id || ''); }}>×</span></button>)}</section><section className="conversation"><div className="messages">{!current?.messages.length && <div className="empty"><img src="/orvix-logo.png"/><h2>How can Orvix help?</h2><p>{rag ? 'Ask questions grounded in your selected knowledge base.' : 'Start a conversation with your configured AI model.'}</p></div>}{current?.messages.map((m, i) => <article className={`message ${m.role}`} key={i}><div className="avatar">{m.role === 'user' ? 'You' : 'O'}</div><Markdown text={m.content || (busy && i === current.messages.length - 1 ? 'Thinking…' : '')}/></article>)}<div ref={bottom}/></div>{error && <div className="error">{error}</div>}<div className="composer"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Message Orvix… (Shift + Enter for a new line)"/><button className="send" disabled={busy || !input.trim()} onClick={send}>↑</button></div></section><ChatSettings rag={rag} settings={settings} setSettings={setSettings} tools={tools} agent={agent} setAgent={setAgent} selectedTools={selectedTools} setSelectedTools={setSelectedTools}/></div></div>
}

function ChatSettings({ rag, settings, setSettings, tools, agent, setAgent, selectedTools, setSelectedTools }) { const set = (k, v) => setSettings(s => ({...s, [k]: v})); return <aside className="settings"><h3>{rag ? 'RAG configuration' : 'Chat settings'}</h3><label>Model<input value={settings.model} onChange={e => set('model', e.target.value)} placeholder="Configured default"/></label><label>Temperature <output>{settings.temperature}</output><input type="range" min="0" max="1" step=".1" value={settings.temperature} onChange={e => set('temperature', +e.target.value)}/></label><label>History rounds<input type="number" min="0" max="20" value={settings.history} onChange={e => set('history', +e.target.value)}/></label>{rag ? <><label>Mode<select value={settings.mode} onChange={e => set('mode', e.target.value)}><option value="kb">Knowledge Base Q&A</option><option value="search">Search Engine Q&A</option></select></label><label>Knowledge base<input value={settings.kb} onChange={e => set('kb', e.target.value)} placeholder="Knowledge base name"/></label><label>Matching items<input type="number" min="1" max="20" value={settings.topK} onChange={e => set('topK', +e.target.value)}/></label><label><input type="checkbox" checked={settings.direct} onChange={e => set('direct', e.target.checked)}/> Return search results only</label></> : <><label><input type="checkbox" checked={agent} onChange={e => setAgent(e.target.checked)}/> Enable Agent / MCP</label>{Object.entries(tools).map(([name, tool]) => <label className="check" key={name}><input type="checkbox" checked={selectedTools.includes(name)} onChange={e => setSelectedTools(x => e.target.checked ? [...x, name] : x.filter(v => v !== name))}/>{tool.title || name}</label>)}</>}</aside> }

function KnowledgeBase() { const [bases, setBases] = useState([]), [selected, setSelected] = useState(''), [files, setFiles] = useState([]), [name, setName] = useState(''), [upload, setUpload] = useState(null), [notice, setNotice] = useState(''); const load = async () => { const data = await listKnowledgeBases(); setBases(data); const kb = selected || data[0]?.kb_name || ''; setSelected(kb); if (kb) setFiles(await listFiles(kb)); }; useEffect(() => { load().catch(e => setNotice(e.message)); }, []); const create = async () => { if (!name.trim()) return; await api.post('/knowledge_base/create_knowledge_base', { knowledge_base_name: name.trim(), vector_store_type: 'faiss', embed_model: '' }); setName(''); setNotice('Knowledge base created.'); load(); }; const uploadFiles = async () => { if (!upload?.length || !selected) return; await uploadDocuments('/knowledge_base/upload_docs', upload, { knowledge_base_name: selected, override: false, to_vector_store: true, chunk_size: 250, chunk_overlap: 50, zh_title_enhance: false, docs: {}, not_refresh_vs_cache: false }); setNotice('Documents uploaded and indexed.'); setUpload(null); load(); }; return <div className="content-page"><header className="page-head"><div><p className="eyebrow">ORGANIZE YOUR CONTEXT</p><h1>Knowledge Base</h1></div></header>{notice && <div className="notice">{notice}</div>}<div className="grid-two"><section className="card"><h2>Create knowledge base</h2><p>Creates the same FastAPI-backed vector store used by the original UI.</p><div className="row"><input value={name} onChange={e => setName(e.target.value)} placeholder="Knowledge base name"/><button className="primary" onClick={create}>Create</button></div></section><section className="card"><h2>Upload documents</h2><p>Files are sent directly to the existing ingestion endpoint.</p><input type="file" multiple onChange={e => setUpload(e.target.files)}/><button className="primary" disabled={!upload?.length || !selected} onClick={uploadFiles}>Upload & index</button></section></div><section className="card"><div className="row"><h2>Documents</h2><select value={selected} onChange={async e => { setSelected(e.target.value); setFiles(await listFiles(e.target.value)); }}>{bases.map(b => <option key={b.kb_name} value={b.kb_name}>{b.kb_name}</option>)}</select><button className="ghost" onClick={async () => { if (selected && confirm(`Delete ${selected}?`)) { await api.post('/knowledge_base/delete_knowledge_base', JSON.stringify(selected)); setSelected(''); load(); }}}>Delete base</button></div>{files.length ? <ul className="file-list">{files.map(f => <li key={f}>{f}<button className="text-button" onClick={async () => { await api.post('/knowledge_base/delete_docs', { knowledge_base_name: selected, file_names: [f], delete_content: true, not_refresh_vs_cache: false }); load(); }}>Remove</button></li>)}</ul> : <p className="muted">No documents in this knowledge base.</p>}</section></div> }

function McpPage() { const [connections, setConnections] = useState([]), [form, setForm] = useState({server_name:'', args:'', description:'', transport:'stdio', timeout:30}); const [notice, setNotice] = useState(''); const load = () => api.get('/api/v1/mcp_connections/').then(unwrap).then(x => setConnections(x?.data || x || [])).catch(e => setNotice(e.message)); useEffect(load, []); const add = async () => { await api.post('/api/v1/mcp_connections/', {...form, args: form.args ? form.args.split(/\s+/) : [], env:{}, enabled:true, config:{}}); setNotice('MCP connection saved.'); setForm({server_name:'',args:'',description:'',transport:'stdio',timeout:30}); load(); }; return <div className="content-page"><header className="page-head"><div><p className="eyebrow">MODEL CONTEXT PROTOCOL</p><h1>MCP Management</h1></div></header>{notice && <div className="notice">{notice}</div>}<section className="card"><h2>Add connector</h2><div className="form-grid"><label>Server command<input value={form.server_name} onChange={e=>setForm({...form,server_name:e.target.value})} placeholder="npx"/></label><label>Arguments<input value={form.args} onChange={e=>setForm({...form,args:e.target.value})} placeholder="-y @modelcontextprotocol/server-filesystem"/></label><label>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Timeout (seconds)<input type="number" value={form.timeout} onChange={e=>setForm({...form,timeout:+e.target.value})}/></label></div><button className="primary" onClick={add} disabled={!form.server_name}>Add connection</button></section><section className="card"><h2>Connections</h2>{connections.length ? connections.map(c => <div className="connection" key={c.id}><div><strong>{c.server_name}</strong><p>{c.description || c.transport} · {c.enabled ? 'Enabled' : 'Disabled'}</p></div><div><button className="ghost" onClick={async()=>{await api.post(`/api/v1/mcp_connections/${c.id}/${c.enabled?'disable':'enable'}`);load();}}>{c.enabled?'Disable':'Enable'}</button><button className="text-button" onClick={async()=>{if(confirm('Remove this connector?')) {await api.delete(`/api/v1/mcp_connections/${c.id}`);load();}}}>Remove</button></div></div>) : <p className="muted">No MCP connections configured.</p>}</section></div> }

function ApiKeys() { return <div className="content-page narrow"><header className="page-head"><div><p className="eyebrow">SERVER CONFIGURATION</p><h1>API Keys</h1></div></header><section className="card"><h2>Keys remain server-managed</h2><p>For security, this React client never reads, stores, or transmits provider secrets. The current Streamlit API-key screen writes directly to <code>model_settings.yaml</code>, which is intentionally not exposed by FastAPI.</p><p className="muted">Configure keys in the existing server settings file, then restart the backend. This preserves the backend authentication and configuration flow without adding a new secret-management API.</p></section></div> }

function App(){ return <BrowserRouter><Layout><Routes><Route path="/chat" element={<ChatPage/>}/><Route path="/rag" element={<ChatPage rag/>}/><Route path="/knowledge-base" element={<KnowledgeBase/>}/><Route path="/mcp" element={<McpPage/>}/><Route path="/api-keys" element={<ApiKeys/>}/><Route path="*" element={<Navigate to="/chat" replace/>}/></Routes></Layout></BrowserRouter> } createRoot(document.getElementById('root')).render(<App/>);
